package org.praxisplatform.uischema.bulk;

/** Closed, persistence-safe causes for a unit-local outcome or common stop. */
public enum BulkUnitReasonCode {
    TARGET_VERSION_CONFLICT, TARGET_STATE_CONFLICT, TARGET_NOT_FOUND, TARGET_DENIED,
    TARGET_INVALID, TARGET_DEPENDENCY_CHANGED, DEADLINE_EXCEEDED, AUTHORIZATION_REVOKED,
    POLICY_BLOCKED, COMMON_GOVERNANCE_CHANGED, COMMON_GOVERNANCE_UNAVAILABLE,
    DEPENDENCY_UNAVAILABLE, UNIT_ROLLED_BACK, RECOVERY_STOPPED, EVALUATOR_UNAVAILABLE,
    STRUCTURAL_REVISION_CHANGED, LEGACY_REASON_NOT_RECORDED
}
